name: Rusty

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-n-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Dependencies
      run: sudo apt-get update -y && sudo apt-get install -y libpcap-dev

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
